{
 "title": "PV",
 "time": { "from": "now-3d", "to": "now+4d" },
 "refresh": "10s",
 "panels": [
  { "title": "Übersicht", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 14, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT\r\n\t`time`,\r\n\tCASE WHEN `Generator` IS NULL THEN NULL WHEN `Generator` > 0 THEN `Generator` ELSE NULL END AS `Gen Produktion`,\r\n\tCASE WHEN `Generator` IS NULL THEN NULL WHEN `Generator` < 0 THEN `Generator` ELSE NULL END AS `Gen Verbrauch`,\r\n\tCASE WHEN `PV Carport` IS NULL THEN NULL WHEN `PV Carport` > 0 THEN `PV Carport` ELSE NULL END AS `PV Carport`,\r\n\tCASE WHEN `PV Dach` IS NULL THEN NULL WHEN `PV Dach` > 0 THEN `PV Dach` ELSE NULL END AS `PV Dach`,\r\n\tCASE WHEN `Generator` IS NULL THEN NULL WHEN `Generator` > 0 THEN `Generator` ELSE 0 END + `PV Carport` + `PV Dach` AS `PV`,\r\n\t`Backup`,\r\n\t`Verbrauch` - `Backup` AS `Verbrauch`,\r\n\tCASE WHEN `Akku` IS NULL THEN NULL WHEN `Akku` < 0 THEN -`Akku` ELSE NULL END AS `Akku laden`,\r\n\tCASE WHEN `Akku` IS NULL THEN NULL WHEN `Akku` > 0 THEN `Akku` ELSE NULL END AS `Akku entladen`,\r\n\tCASE WHEN `Netz` IS NULL THEN NULL WHEN `Netz` > 0 THEN `Netz` ELSE NULL END AS `Netzbezug`,\r\n\tCASE WHEN `Netz` IS NULL THEN NULL WHEN `Netz` < 0 THEN -`Netz` ELSE NULL END AS `Einspeisung`,\r\n\tCASE WHEN `Inverter AC` IS NULL THEN NULL ELSE `Inverter AC` END AS `Inverter AC`,\r\n\t`Akku SOC`,\r\n\t`Akku V`\r\nFROM\r\n\t(SELECT\r\n\t  `unix_ts` - `unix_ts` % $__interval_ms AS `time`,\r\n\t  AVG(`gen_P`) AS `Generator`,\r\n\t  AVG(`carport_P`) AS `PV Carport`,\r\n\t  AVG(`roof_P`) AS `PV Dach`,\r\n\t  AVG(`battery_P`) AS `Akku`,\r\n\t  AVG(`em_grid_P`*1000) AS `Netz`,\r\n\t\tAVG(`backup_P`) AS `Backup`,\r\n\t  AVG(`load_total_P`) AS `Verbrauch`,\r\n\t  AVG(`battery_SOC`) AS `Akku SOC`,\r\n\t\tAVG(`battery_V`*0.01) AS `Akku V`,\r\n\t\tAVG(`battery_discharge_total_E`) AS `battery_discharge_total_E`,\r\n\t\tAVG(`inverter_P`) AS `Inverter AC`\r\n\tFROM\r\n\t  log.pv\r\n\tWHERE\r\n\t  `unix_ts` > ($__unixEpochFrom()*1000) AND `unix_ts` < ($__unixEpochTo()*1000)\r\n\tGROUP BY\r\n\t\t`time`\r\n\tORDER BY\r\n\t  `time` DESC) AS `t`"
    },
    {
     "rawSql": "SELECT\r\n\t  `unix_ts` - `unix_ts` % $__interval_ms AS `time`,\r\n\t  AVG(`elevation`) AS `sun_elevation`,\r\n\t\tAVG(`azimuth`) AS `sun_azimuth`\r\n\tFROM\r\n\t  `log`.`sun`\r\n\tWHERE\r\n\t  `unix_ts` > (($__unixEpochFrom()-300)*1000) AND `unix_ts` < (($__unixEpochTo()+300)*1000)\r\n\tGROUP BY\r\n\t\t`time`\r\n\tORDER BY\r\n\t  `time` DESC"
    },
    {
     "rawSql": "SELECT\r\n\t  (`timestamp` - `timestamp` % $__interval_ms)-1800000 AS `time`,\r\n\t\tAVG(`PPPP`/100000) AS `PPPP`,\r\n\t\tAVG(`TTT`-273.15) AS `TTT`,\r\n\t\tCASE WHEN AVG(`RR1c`) = 0 THEN NULL ELSE -AVG(`RR1c`) END AS `RR1c`,\r\n\t\tAVG(`R101`) AS `R101`,\r\n\t\tAVG(`Rad1h`/3.6) AS `Rad1h`,\r\n\t\tAVG(`SunD1`/3600) AS `SunD1`,\r\n\t\tCASE WHEN FROM_UNIXTIME(AVG(`timestamp`) / 1000-1800) > NOW() THEN AVG(`Neff`) ELSE NULL END AS `Neff`\r\n\tFROM\r\n\t  `log`.`weather`\r\n\tWHERE\r\n    `location` = 'N8381' AND\r\n\t  `timestamp` > (($__unixEpochFrom()-7200)*1000) AND `timestamp` < (($__unixEpochTo()+7200)*1000)\r\n\tGROUP BY\r\n\t\t`time`\r\n\tORDER BY\r\n\t  `time` DESC"
    }
   ]
  },
  {
   "title": "Produktion",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT gen_P+carport_P+roof_P AS `val` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 } },
  {
   "title": "Verbrauch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT load_total_P AS `load_total_P` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Akku",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT battery_P AS `battery_P` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Akku",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT battery_V*0.01 AS `battery_V` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 60*12 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Akku",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT `battery_SOC` AS `battery_SOC` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 60*12 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Netz",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT em_grid_P AS `grid_P` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Inverter AC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT inverter_P AS `inverter_P` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Backup",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT backup_P AS `backup_P` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 9, "x": 15, "y": 13 } },
  {
   "title": "Dach",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT roof_P AS `roof_P` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Carport",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT carport_P AS `carport_P` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Generator",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT gen_P AS `gen_P` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  `unix_ts` - `unix_ts` % $__interval_ms AS `time`,\r\n  (AVG(heatsink_T) -1000) * 0.1 AS `Heatsink`,\r\n  (AVG(battery_T) -1000) * 0.1 AS `Battery`,\r\n  (AVG(DC_transformer_T) -1000) * 0.1 AS `DC Transformer`,\r\n  MAX((`status` & 8) >> 3)+0 AS `Grid status`,\r\n  MAX((`status` & 16) >> 4) AS `Gen status`,\r\n  MAX((`status` & 32) >> 5) AS `Something status`\r\nFROM\r\n  `log`.`pv`\r\nWHERE\r\n  `unix_ts` > ($__unixEpochFrom()*1000) AND `unix_ts` < ($__unixEpochTo()*1000)\r\nGROUP BY\r\n  `time`\r\nORDER BY\r\n  `time` DESC"
    }
   ]
  },
  {
   "title": "Dach",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT roof_V*0.1 AS `roof_V` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Carport",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT carport_V*0.1 AS `carport_V` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  `unix_ts` - `unix_ts` % $__interval_ms AS `time`,\r\n  AVG(`Ts`) AS `Soll`,\r\n  AVG(`T5U`) AS `Oben`,\r\n  AVG(`T5L`) AS `Unten`,\r\n  AVG(`Tx`) AS `Aktuell`,\r\n  AVG(`T3`) AS `Kondensator`,\r\n  AVG(`T4`) AS `Raum`,\r\n  AVG(`Tp`) AS `Kompressor`,\r\n  AVG(`Th`) AS `Ansaugung`,\r\n  AVG(`pmv`) AS `pmv`,\r\n  MAX((`status1` & 1) >> 0) AS `Kompressor Status`,\r\n  MAX((`status1` & 2) >> 1) AS `Heizstab Status`,\r\n  CAST(CASE WHEN (MAX((`status1` & (8+16+32)) >> 3)) = 4 THEN 3 ELSE MAX((`status1` & (8+16+32)) >> 3) END AS SIGNED ) AS `Lüfter`\r\nFROM\r\n  `log`.`styleboiler`\r\nWHERE\r\n  `unix_ts` > ($__unixEpochFrom()*1000) AND `unix_ts` < ($__unixEpochTo()*1000)\r\nGROUP BY\r\n  `time`\r\nORDER BY\r\n  `time` DESC"
    }
   ]
  },
  {
   "title": "Aktuell",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT `Tx` AS `Tx` FROM `log`.`styleboiler` WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 4, "w": 3, "x": 18, "y": 23 } },
  {
   "title": "Kompressor",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT `Tp` AS `Tp` FROM `log`.`styleboiler` WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Soll",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT `Ts` AS `Ts` FROM `log`.`styleboiler` WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Kondensator",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT `T3` AS `T3` FROM `log`.`styleboiler` WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Raum",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT `T4` AS `T4` FROM `log`.`styleboiler` WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Ansaugung",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT `Th` AS `Th` FROM `log`.`styleboiler` WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Oben",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT `T5U` AS `T5U` FROM `log`.`styleboiler` WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Unten",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT `T5L` AS `T5L` FROM `log`.`styleboiler` WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT\r\n\t`time`,\r\n\tCASE WHEN `inverter_p1_P` IS NULL THEN NULL WHEN `inverter_p1_P` < 0 THEN `inverter_p1_P` ELSE 0 END AS `inverter_p1_P_in`,\r\n\tCASE WHEN `inverter_p1_P` IS NULL THEN NULL WHEN `inverter_p1_P` > 0 THEN  `inverter_p1_P` ELSE 0 END AS `inverter_p1_P_out`,\r\n\tCASE WHEN `inverter_p2_P` IS NULL THEN NULL WHEN `inverter_p2_P` < 0 THEN `inverter_p2_P` ELSE 0 END AS `inverter_p2_P_in`,\r\n\tCASE WHEN `inverter_p2_P` IS NULL THEN NULL WHEN `inverter_p2_P` > 0 THEN  `inverter_p2_P` ELSE 0 END AS `inverter_p2_P_out`,\r\n\tCASE WHEN `inverter_p3_P` IS NULL THEN NULL WHEN `inverter_p3_P` < 0 THEN `inverter_p3_P` ELSE 0 END AS `inverter_p3_P_in`,\r\n\tCASE WHEN `inverter_p3_P` IS NULL THEN NULL WHEN `inverter_p3_P` > 0 THEN  `inverter_p3_P` ELSE 0 END AS `inverter_p3_P_out`,\r\n\tCASE WHEN `inverter_P` IS NULL THEN NULL WHEN `inverter_P` < 0 THEN -`inverter_P` ELSE 0 END AS `inverter_P_in`,\r\n\tCASE WHEN `inverter_P` IS NULL THEN NULL WHEN `inverter_P` > 0 THEN  `inverter_P` ELSE 0 END AS `inverter_P_out`\r\nFROM\r\n\t(SELECT\r\n\t  `unix_ts` - `unix_ts` % $__interval_ms AS `time`,\r\n\t  AVG(`inverter_p1_P`) AS `inverter_p1_P`,\r\n\t  AVG(`inverter_p2_P`) AS `inverter_p2_P`,\r\n\t  AVG(`inverter_p3_P`) AS `inverter_p3_P`,\r\n\t  AVG(`inverter_P`) AS `inverter_P`\r\n\tFROM\r\n\t  `log`.`pv`\r\n\tWHERE\r\n\t  `unix_ts` > ($__unixEpochFrom()*1000) AND `unix_ts` < ($__unixEpochTo()*1000)\r\n\tGROUP BY\r\n\t\t`time`\r\n\tORDER BY\r\n\t  `time` DESC) AS `t`"
    }
   ]
  },
  {
   "title": "Phase 1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT inverter_p1_P AS `inverter_p1_P` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Phase 1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT inverter_p1_V*0.1 AS `inverter_p1_V` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Inverter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT inverter_frq*0.01 AS `inverter_frq` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Phase 2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT inverter_p2_P AS `inverter_p2_P` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Phase 2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT inverter_p2_V*0.1 AS `inverter_p2_V` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT load_frq*0.01 AS `load_frq` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT\r\n\t  `unix_ts` - `unix_ts` % $__interval_ms AS `time`,\r\n\t  0.1*AVG(`inverter_p1_V`) AS `inverter_p1_V`,\r\n\t  0.1*AVG(`inverter_p2_V`) AS `inverter_p2_V`,\r\n\t  0.1*AVG(`inverter_p3_V`) AS `inverter_p3_V`\r\n\tFROM\r\n\t  `log`.`pv`\r\n\tWHERE\r\n\t  `unix_ts` > ($__unixEpochFrom()*1000) AND `unix_ts` < ($__unixEpochTo()*1000)\r\n\tGROUP BY\r\n\t\t`time`\r\n\tORDER BY\r\n\t  `time` DESC"
    }
   ]
  },
  {
   "title": "Phase 3",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT inverter_p3_P AS `inverter_p3_P` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Phase 3",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT inverter_p3_V*0.1 AS `inverter_p3_V` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Netz",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT em_frq AS `grid_frq` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT\r\n\t  `unix_ts` - `unix_ts` % $__interval_ms AS `time`,\r\n\t  0.01*AVG(`inverter_frq`) AS `inverter_frq`,\r\n\t  0.01*AVG(`load_frq`) AS `load_frq`,\r\n\t  AVG(`em_frq`) AS `grid_frq`\r\n\tFROM\r\n\t  `log`.`pv`\r\n\tWHERE\r\n\t  `unix_ts` > ($__unixEpochFrom()*1000) AND `unix_ts` < ($__unixEpochTo()*1000)\r\n\tGROUP BY\r\n\t\t`time`\r\n\tORDER BY\r\n\t  `time` DESC"
    }
   ]
  },
  {
   "title": "Inverter AC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT inverter_P AS `inverter_P` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Uhrzeit Versatz",
   "type": "table",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT UNIX_TIMESTAMP(NOW())-UNIX_TIMESTAMP(`inverter_timestamp`) AS `Offset` FROM log.pv_values LIMIT 1"
    }
   ]
  },
  { "title": "Historie", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Energie / Tag",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    DATE(`date`) AS `date`,\r\n    `load` * 0.1 AS `Verbrauch`,\r\n    `pv` * 0.1 AS `PV`,\r\n    `gen` * 0.1 AS `Generator`,\r\n    COALESCE( `em_import`, `grid_in` * 0.1 ) AS `Netzbezug`,\r\n    COALESCE( `em_export`, `grid_out` * 0.1 ) AS `Einspeisung`,\r\n    `battery_charge` * 0.1 AS `Akku laden`,\r\n    `battery_discharge` * 0.1 AS `Akku entladen`\r\nFROM\r\n    `log`.`pv_E`\r\nWHERE\r\n    $__timeFilter(date)"
    }
   ]
  },
  {
   "title": "Energie / Monat",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    UNIX_TIMESTAMP(DATE(CONCAT(YEAR(`date`),'-',MONTH(`date`),'-01')))+0*24*3600 AS `time`,\r\n    SUM(`load`) * 0.1 AS `Verbrauch`,\r\n    SUM(`pv`) * 0.1 AS `PV`,\r\n    SUM(`gen`) * 0.1 AS `Generator`,\r\n    SUM( COALESCE( `em_import`, `grid_in` * 0.1 ) ) AS `Netzbezug`,\r\n    SUM( COALESCE( `em_export`, `grid_out` * 0.1 ) ) AS `Einspeisung`,\r\n    SUM(`battery_charge`) * 0.1 AS `Akku laden`,\r\n    SUM(`battery_discharge`) * 0.1 AS `Akku entladen`\r\nFROM\r\n    `log`.`pv_E`\r\nWHERE\r\n    $__timeFilter(date)\r\nGROUP BY\r\n    `time`\r\n"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT\r\n\t  UNIX_TIMESTAMP(`timestamp`) * 1000 - (UNIX_TIMESTAMP(`timestamp`) * 1000) % $__interval_ms AS `time`,\r\n\t  AVG(CASE WHEN `packetsOk` = 1 THEN NULL ELSE 1-`packetsOk` END ) AS `packetLossNulled`,\r\n\t\tAVG(1-`packetsOk`) AS `packetLoss`,\r\n    AVG(`rttMin`) AS `rttMin`,\r\n    AVG(`rttMax`) AS `rttMax`,\r\n\t  AVG(`rttAvg`) AS `rttAvg`\r\n\tFROM\r\n\t  `log`.`net`\r\n\tWHERE\r\n\t  $__timeFilter(timestamp)\r\n\tGROUP BY\r\n\t\t`time`\r\n\tORDER BY\r\n\t  `time` DESC"
    }
   ]
  }
 ]
}